### ISSUE TITLE
Swift->Swift sync of SLOs does not detect already uploaded large objects

### ISSUE THREAD

**Issue by thiagodasilva** [swiftstack/1space#169]
Already uploaded large objects currently are re-uploaded because we don't properly check whether the object has been uploaded (we only compare the ETag of the manifests, which differs if the segment containers differ). In those cases, we should fetch both manifests and compare them, adjusting for the segment container differences.

**Comment by timuralp** [comment]
Closed via https://github.com/swiftstack/1space/pull/166/commits/1ecd2e458c46781d361978347c75ce740335a4b2
