### ISSUE TITLE
Improve 1space sync/lifecycle handling of many-thousand mappings

### ISSUE THREAD

**Issue by thiagodasilva** [swiftstack/1space#170]
Currently, we iterate over each container individually, performing the uploads there in parallel. Just to scan these containers, with no additional work to be done, takes ~2.5 minutes in our experiments.

We have to add some parallelism to the container handling to improve on this. We can either have multiple enumerating threads, following our existing model. Or try to re-architect this to use a single work queue into which we put objects with a profile to be used for the upload.

**Comment by timuralp** [comment]
This has already been merged in. Closing.

**Comment by timuralp** [comment]
Sorry -- was thinking of the wrong issue.

**Comment by timuralp** [comment]
Right the first time :(
