### ISSUE TITLE
[Swift] Allow for expiring moved objects as part of archive/lifecycle

### ISSUE THREAD

**Issue by thiagodasilva** [swiftstack/1space#172]
We should allow objects to be expired from remote object stores after they have been moved as part of the archive/lifecycle workflow. In the case of Swift, that means we can set the `x-delete-at` header to a user supplied value (e.g. delete all archived objects after 1 year).

**Comment by timuralp** [comment]
Let's keep this specific to Swift -- edited the description accordingly.

**Comment by mdegerne** [comment]
PR: https://github.com/swiftstack/1space/pull/165
