### ISSUE TITLE
Distribute migrator work across multiple nodes per container

### ISSUE THREAD

**Issue by thiagodasilva** [swiftstack/1space#175]
The migrator currently splits up work at the container level, where each node is responsible for a specific container in the migration. No other nodes attempt to replicate this work and if the container has many objects, that work cannot be split up across other nodes that may be idle. The goal here is to re-think how we split up the work, such that we can tolerate node failures and cope with large containers better. We should consider an approach similar to the `ContainerCrawler` library.

**Comment by timuralp** [comment]
Closed for now via #134
