### ISSUE TITLE
GET on container with swift migration profile does not automatically migrate object

### ISSUE THREAD

**Issue by thiagodasilva** [swiftstack/1space#193]
Migration profiles are set to `restore_objects` by default[1]. But currently, profiles with swift protocol will not migrate objects automatically on a GET[2]. Notice that line 375:
> `_verify_objects(conn_local, migration['container'])`

should have caused a migration, thus line 385: 
> `self.assertFalse(_check_objects_copied(conn_noshunt, migration['container']))` 

should have failed.

[1] - https://github.com/swiftstack/1space/blob/s3_migrations/s3_sync/shunt.py#L150
[2] - https://github.com/swiftstack/1space/blob/s3_migrations/test/integration/test_migrator.py#L372,L384

**Comment by timuralp** [comment]
@thiagodasilva can you point the links on master rather than the `s3_migrations` branch? Is this still an issue?

**Comment by mdegerne** [comment]
I think I see where the confusion is coming. The call to _check_objects_copied does not do a get on the objects, it only does a container listing. This, correctly, doesn't move the objects prematurely.
